export const data = [
  {
    id: 1,
    img: 'https://images.unsplash.com/photo-1577221084712-45b0445d2b00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=698&q=80',
    nameEjercicio: 'Abdominales',
    descripcion: 'Realiza abdominales para fortalecer los músculos abdominales. Recuerda mantener una postura adecuada y respirar correctamente durante el ejercicio.',
    duracion: 120,
    repeticiones: '2x3',
    categoria: 'Espalda',
  },
  {
    id: 2,
    img: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=687&amp;q=80',
    nameEjercicio: 'Barra',
    descripcion: 'Haz levantamientos en barra para trabajar los músculos de la espalda y los brazos. Este ejercicio es ideal para desarrollar fuerza y mejorar tu resistencia. Asegúrate de mantener una buena técnica y progresar gradualmente en el peso utilizado.',
    duracion: 120,
    repeticiones: '3x4',
    categoria: 'Espalda',
  },
  {
    id: 3,
    img: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=870&amp;q=80',
    nameEjercicio: 'Peso muerto',
    descripcion: 'Realiza el ejercicio de peso muerto para fortalecer la musculatura de la espalda, los glúteos y los isquiotibiales. Este es un ejercicio compuesto que te ayudará a desarrollar fuerza y mejorar tu postura. Asegúrate de mantener una técnica adecuada y progresar gradualmente en el peso utilizado.',
    duracion: 180,
    repeticiones: '2x5',
    categoria: 'Espalda',
  },
  {
    id: 4,
    img: 'https://plus.unsplash.com/premium_photo-1679635697818-2cdd42cbc6e0?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=870&amp;q=80',
    nameEjercicio: 'Press de pierna',
    descripcion: 'Realiza el ejercicio de press de pierna para fortalecer los músculos de las piernas, incluyendo los cuádriceps, los isquiotibiales y los glúteos. Este ejercicio te ayudará a desarrollar fuerza y potencia en la parte inferior del cuerpo. Asegúrate de mantener una técnica adecuada y utilizar un rango de movimiento completo.',
    duracion: 10,
    repeticiones: '2x10',
    categoria: 'Espalda',
  },
  {
    id: 5,
    img: 'https://images.unsplash.com/photo-1593494418158-38517e0b23ef?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=388&amp;q=80',
    nameEjercicio: 'Tiro con cuerda',
    descripcion: 'Realiza el ejercicio de tiro con cuerda para trabajar los músculos de los brazos, los hombros y los músculos centrales. Este ejercicio te ayudará a mejorar tu resistencia y coordinación. Asegúrate de mantener una postura estable y utilizar un rango de movimiento completo durante el ejercicio.',
    duracion: 30,
    repeticiones: '2x20',
    categoria: 'Cardio',
  },
  {
    id: 6,
    img: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=725&amp;q=80',
    nameEjercicio: 'Ejercicio en T',
    descripcion: 'Realiza el ejercicio en T para trabajar los músculos de la espalda, los hombros y los músculos centrales. Este ejercicio te ayudará a mejorar tu postura y estabilidad. Asegúrate de mantener una técnica adecuada y controlar el movimiento en todo momento.',
    duracion: 35,
    repeticiones: '2x10',
    categoria: 'Cardio',
  },
  {
    id: 7,
    img: 'https://plus.unsplash.com/premium_photo-1666736569549-c106f7921d87?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=388&amp;q=80',
    nameEjercicio: 'Sentadillas',
    descripcion: 'Realiza sentadillas para trabajar los músculos de las piernas y los glúteos. Este ejercicio es excelente para desarrollar fuerza y potencia en la parte inferior del cuerpo. Asegúrate de mantener una técnica adecuada y utilizar un rango de movimiento completo.',
    duracion: 300,
    repeticiones: '3x6',
    categoria: 'Piernas',
  },
  {
    id: 8,
    img: 'https://images.unsplash.com/photo-1518644961665-ed172691aaa1?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=870&amp;q=80',
    nameEjercicio: 'Flexiones',
    descripcion: 'Realiza flexiones para trabajar los músculos del pecho, los brazos y los hombros. Este ejercicio es excelente para desarrollar fuerza en la parte superior del cuerpo. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 300,
    repeticiones: '3x8',
    categoria: 'Cardio',
  },
  {
    id: 9,
    img: 'https://images.unsplash.com/photo-1626444231642-6bd985bca16a?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=869&amp;q=80',
    nameEjercicio: 'Plancha',
    descripcion: 'Realiza la plancha para fortalecer los músculos centrales, incluyendo el abdomen y la espalda baja. Este ejercicio es excelente para mejorar tu estabilidad y resistencia. Asegúrate de mantener una postura recta y contraer los músculos correctamente durante el ejercicio.',
    duracion: 180,
    repeticiones: '2x30',
    categoria: 'Core',
  },
  {
    id: 10,
    img: 'https://cdn.pixabay.com/photo/2016/09/21/22/59/sport-1685936_960_720.jpg 1x, https://cdn.pixabay.com/photo/2016/09/21/22/59/sport-1685936_1280.jpg',
    nameEjercicio: 'Burpees',
    descripcion: 'Realiza burpees para trabajar todo el cuerpo y mejorar tu resistencia. Este ejercicio combina flexiones, saltos y sentadillas, y es ideal para quemar calorías y fortalecer los músculos. Asegúrate de mantener un ritmo constante y una técnica adecuada durante el ejercicio.',
    duracion: 60,
    repeticiones: '3x8',
    categoria: 'Cardio',
  },
  {
    id: 11,
    img: 'https://images.unsplash.com/photo-1593494418158-38517e0b23ef?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=388&amp;q=80',
    nameEjercicio: 'Saltos',
    descripcion: 'Realiza saltos para trabajar los músculos de las piernas y mejorar tu resistencia cardiovascular. Este ejercicio es excelente para quemar calorías y fortalecer los músculos de las piernas. Asegúrate de mantener una buena técnica y aterrizar suavemente en cada salto.',
    duracion: 20,
    repeticiones: '3x10',
    categoria: 'Cardio',
  },
  {
    id: 12,
    img: 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=725&amp;q=80',
    nameEjercicio: 'Mountain climbers',
    descripcion: 'Realiza mountain climbers para trabajar los músculos centrales y mejorar tu resistencia cardiovascular. Este ejercicio es excelente para fortalecer los músculos del abdomen y mejorar tu coordinación. Asegúrate de mantener una postura adecuada y realizar el movimiento de forma controlada.',
    duracion: 30,
    repeticiones: '3x12',
    categoria: 'Cardio',
  },
  {
    id: 13,
    img: 'https://plus.unsplash.com/premium_photo-1666736569549-c106f7921d87?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=388&amp;q=80',
    nameEjercicio: 'Flexiones de tríceps',
    descripcion: 'Realiza flexiones de tríceps para fortalecer los músculos de los brazos y los hombros. Este ejercicio se enfoca en la parte posterior de los brazos y es excelente para desarrollar fuerza en esa área. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 20,
    repeticiones: '3x10',
    categoria: 'Cardio',
  },
  {
    id: 14,
    img: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=687&amp;q=80',
    nameEjercicio: 'Remo',
    descripcion: 'Haz remo para trabajar los músculos de la espalda y los brazos. Este ejercicio es ideal para desarrollar fuerza y mejorar tu resistencia. Asegúrate de mantener una buena técnica y progresar gradualmente en el peso utilizado.',
    duracion: 120,
    repeticiones: '3x5',
    categoria: 'Espalda',
  },
  {
    id: 15,
    img: 'https://cdn.pixabay.com/photo/2016/09/21/22/59/sport-1685936_960_720.jpg 1x, https://cdn.pixabay.com/photo/2016/09/21/22/59/sport-1685936_1280.jpg',
    nameEjercicio: 'Zancadas',
    descripcion: 'Realiza zancadas para trabajar los músculos de las piernas, incluyendo los cuádriceps, los isquiotibiales y los glúteos. Este ejercicio es excelente para desarrollar fuerza y equilibrio en la parte inferior del cuerpo. Asegúrate de mantener una técnica adecuada y utilizar un rango de movimiento completo.',
    duracion: 25,
    repeticiones: '3x12',
    categoria: 'Piernas',
  },
  {
    id: 16,
    img: 'https://images.unsplash.com/photo-1571689652090-69cf3da3d53b?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=700&amp;q=80',
    nameEjercicio: 'Abdominales',
    descripcion: 'Realiza abdominales para fortalecer los músculos del abdomen. Este ejercicio es excelente para mejorar la estabilidad del core y desarrollar fuerza en esa área. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 15,
    repeticiones: '3x15',
    categoria: 'Core',
  },
  {
    id: 17,
    img: 'https://images.unsplash.com/photo-1593991041736-28f3a34a5b21?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=688&amp;q=80',
    nameEjercicio: 'Flexiones de pectoral',
    descripcion: 'Realiza flexiones de pectoral para trabajar los músculos del pecho, los brazos y los hombros. Este ejercicio se enfoca en la parte frontal del pecho y es excelente para desarrollar fuerza en esa área. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 20,
    repeticiones: '3x10',
    categoria: 'Cardio',
  },
  {
    id: 18,
    img: 'https://images.unsplash.com/photo-1558980669-afa115ee12f4?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=80',
    nameEjercicio: 'Elevaciones de hombros',
    descripcion: 'Realiza elevaciones de hombros para trabajar los músculos de los hombros. Este ejercicio es excelente para desarrollar fuerza y estabilidad en esa área. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 15,
    repeticiones: '3x12',
    categoria: 'Cardio',
  },
  {
    id: 19,
    img: 'https://images.unsplash.com/photo-1612363060148-00e2b90d1e8f?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=634&amp;q=80',
    nameEjercicio: 'Sentadillas',
    descripcion: 'Realiza sentadillas para trabajar los músculos de las piernas y los glúteos. Este ejercicio es fundamental para desarrollar fuerza y potencia en la parte inferior del cuerpo. Asegúrate de mantener una técnica adecuada y utilizar un rango de movimiento completo.',
    duracion: 30,
    repeticiones: '3x10',
    categoria: 'Piernas',
  },
  {
    id: 20,
    img: 'https://images.unsplash.com/photo-1611422684445-b7ebc06cb7c9?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=800&amp;q=80',
    nameEjercicio: 'Bicicleta estática',
    descripcion: 'Realiza ejercicio en una bicicleta estática para mejorar tu resistencia cardiovascular y fortalecer los músculos de las piernas. Este ejercicio es de bajo impacto y es ideal para quemar calorías. Asegúrate de ajustar el nivel de resistencia de acuerdo a tu nivel de condición física.',
    duracion: 30,
    repeticiones: '3x5 minutos',
    categoria: 'Cardio',
  },
  {
    id: 21,
    img: 'https://cdn.pixabay.com/photo/2014/11/17/13/17/crossfit-534615_960_720.jpg',
    nameEjercicio: 'Flexiones diamante',
    descripcion: 'Realiza flexiones diamante para trabajar los músculos del pecho y los tríceps. Este ejercicio se enfoca en la parte central del pecho y es excelente para desarrollar fuerza en esa área. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 20,
    repeticiones: '3x10',
    categoria: 'Cardio',
  },
  {
    id: 22,
    img: 'https://cdn.pixabay.com/photo/2016/11/21/14/39/exercise-1845759_960_720.jpg 1x, https://cdn.pixabay.com/photo/2016/11/21/14/39/exercise-1845759_1280.jpg',
    nameEjercicio: 'Elevaciones laterales',
    descripcion: 'Realiza elevaciones laterales para trabajar los músculos de los hombros. Este ejercicio es excelente para desarrollar fuerza y definición en esa área. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 15,
    repeticiones: '3x12',
    categoria: 'Cardio',
  },
  {
    id: 23,
    img: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?ixlib=rb-4.0.3&amp;ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&amp;auto=format&amp;fit=crop&amp;w=687&amp;q=80',
    nameEjercicio: 'Burpees',
    descripcion: 'Realiza burpees para un ejercicio de cuerpo completo que te ayudará a mejorar tu resistencia cardiovascular y quemar calorías. Este ejercicio combina saltos, flexiones y sentadillas para trabajar varios grupos musculares al mismo tiempo. Asegúrate de mantener una buena técnica y realizar el movimiento de forma fluida.',
    duracion: 30,
    repeticiones: '3x8',
    categoria: 'Cardio',
  },
  {
    id: 24,
    img: 'https://images.unsplash.com/photo-1577221084712-45b0445d2b00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=698&q=80',
    nameEjercicio: 'Plancha',
    descripcion: 'Realiza planchas para fortalecer los músculos del core, incluyendo los abdominales, la espalda y los glúteos. Este ejercicio es excelente para mejorar la estabilidad y la resistencia en el core. Asegúrate de mantener una técnica adecuada y controlar la respiración durante el ejercicio.',
    duracion: 60,
    repeticiones: '3x1 minuto',
    categoria: 'Core',
  },
];
